### ISSUE TITLE
Do I expect OE 3.1 to warp when there is a partially synced DB?

### ISSUE THREAD

**Issue by yorickdowne** [openethereum/backport-3.1#62]
- OE 3.1rc1
- Ubuntu 20.04.01
- Coming from 2.5.13

2.5.13 was not fully synced.

2.5.13 had gotten to #6843802, then was stopped, --bootnodes were added, and it was started again. OE 2.5.13 started syncing snapshots, "warping", as expected. It did not complete this and was stopped again ~ snapshot 1000.

My expected behavior with OE 3.1 after db conversion was that it, too, would start to "warp" on the partially synced DB and start syncing from snapshots, but it did not do that. Instead, it continued the sync from #6843803, without an attempt to use snapshots and warp.

```
Sep 25 10:59:33 ethlinux systemd[1]: Started OpenEthereum.
Sep 25 10:59:33 ethlinux openethereum[151520]: 2020-09-25 10:59:33  Starting OpenEthereum/v3.1.0-rc1-stable-51817baec-20200925/x86_64-linux-gnu/rustc1.46.0
Sep 25 10:59:33 ethlinux openethereum[151520]: 2020-09-25 10:59:33  Keys path /var/lib/openethereum/keys/ethereum
Sep 25 10:59:33 ethlinux openethereum[151520]: 2020-09-25 10:59:33  DB path /var/lib/openethereum/chains/ethereum/db/906a34e69aec8c0d
Sep 25 10:59:33 ethlinux openethereum[151520]: 2020-09-25 10:59:33  State DB configuration: fast
Sep 25 10:59:33 ethlinux openethereum[151520]: 2020-09-25 10:59:33  Operating mode: active
Sep 25 10:59:33 ethlinux openethereum[151520]: 2020-09-25 10:59:33  Configured for Ethereum using Ethash engine
Sep 25 10:59:34 ethlinux openethereum[151520]: 2020-09-25 10:59:34  Public node URL: enode://e5190d76f3dde992159944389e3c3c10edce1d0b762644b4d302875fbcf2f37283f7896ed005d87a8275e10eef0fa04a6845b04b3061eb4bd88e24d95cdeb41f@PUBIP:30304
Sep 25 10:59:34 ethlinux openethereum[151520]: 2020-09-25 10:59:34  Removed existing file '/var/lib/openethereum/jsonrpc-1.ipc'.
Sep 25 10:59:34 ethlinux openethereum[151520]: 2020-09-25 10:59:34  Updated conversion rate to Ξ1 = US$345.08 (13799422 wei/gas)
Sep 25 10:59:44 ethlinux openethereum[151520]: 2020-09-25 10:59:44  Syncing #6843803 0xaf0f…0b44     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  124 Qed  #6843930   11/25 peers     81 KiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
```

After stopping OE 3.1, clearing the base directory, and starting it again, it started to sync from snapshot.

Is this behavior "as designed", or considered a bug?

**Comment by adria0** [comment]
Is this a duplicate of #63?

**Comment by yorickdowne** [comment]
No these are different behaviors.

#63: Starting from clean datadir, if snapshot is interrupted, OE will not be able to resume snapshot. It will also not be able to sync at all. Datadir needs to be cleaned out again for OE to succeed on snapshot after restart.

This: Starting from partially synced 2.5.13 DB, OE will not attempt to snapshot (like OE 2.5.13 did), but instead will resume sync from where 2.5.13 was partial.

**Comment by adria0** [comment]
@yorickdowne, the current behavior AFAIK is:
- only if database is fresh & empty start to warp sync
- if in the process of warp syncing there are no peers available for warm syncing, go to normal sync, after 5 seconds

**Comment by yorickdowne** [comment]
Got it, thank you. This differs from 2.5.13, then. 2.5.13 would warp sync even if db was not fresh & empty.

The behavior as-is in 3.1 is fine, I think.
